name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build Rust Project
        working-directory: src/backend
        run: cargo build --release

      - name: Run Rust Tests
        working-directory: src/backend
        run: cargo test

      - name: Build Docker Image
        run: docker-compose -f docker-compose.yml build

      - name: Run Docker Compose Tests
        run: docker-compose -f docker-compose.yml up --abort-on-container-exit