name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build Rust Project
        working-directory: src/backend
        run: cargo build --release

      - name: Run Rust Tests
        working-directory: src/backend
        run: cargo test

      - name: Build Docker Image
        working-directory: src/backend
        run: |
          docker build -t character-builder .

      - name: Test Docker Image
        run: |
          docker run --rm character-builder